apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-pool
  namespace: metallb-system
spec:
  addresses:
    # IPs outside the router's DHCP range (.100-.249)
    - 192.168.1.250-192.168.1.253
