repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: longhorn
    url: https://charts.longhorn.io
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    values:
      - cluster/core-system/traefik/values.yaml

  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    values:
      - cluster/core-system/longhorn/values.yaml

  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    values:
      - cluster/argocd/values.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    values:
      - cluster/monitoring/prometheus-values.yaml
