apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.5.4
    helm:
      values: |
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 1
        csi:
          kubeletRootDir: /var/lib/kubelet
  
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
