apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    # Upstream Helm chart
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 39.0.6
      helm:
        valueFiles:
          - $values/cluster/core-system/traefik/values.yaml
    # Git ref that provides $values for the valueFiles path above
    - repoURL: https://github.com/TuckerWarlock/raspi-k3s-cluster
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
