apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
spec:
  project: default
  
  # Source: This repo, cluster/argocd/ (Kustomization)
  source:
    repoURL: https://github.com/TuckerWarlock/raspi-k3s-cluster
    path: cluster/argocd
    targetRevision: main
  
  # Destination: This cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  # Auto-sync: Keep cluster in sync with Git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
