apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Core infrastructure Applications (run on pi4controller only)
resources:
  - metallb.yaml
  - traefik.yaml
  - longhorn.yaml
  - monitoring.yaml
